# Frontend - Next.js
FROM node:20-alpine AS dependencies
WORKDIR /app
RUN corepack enable pnpm

COPY pnpm-lock.yaml ./
RUN pnpm fetch --prod

FROM node:20-alpine AS builder
WORKDIR /app
RUN corepack enable pnpm

COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

RUN pnpm install --frozen-lockfile --offline
RUN pnpm run build --filter=web

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
EXPOSE 3000

RUN corepack enable pnpm

COPY --from=builder /app/apps/web/.next ./apps/web/.next
COPY --from=builder /app/apps/web/package.json ./apps/web/package.json
COPY --from=builder /app/apps/web/public ./apps/web/public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

WORKDIR /app/apps/web

CMD ["pnpm", "start"]
