# Backend - Fastify
FROM node:20-alpine AS dependencies
WORKDIR /app
RUN corepack enable pnpm

COPY pnpm-lock.yaml ./
RUN pnpm fetch --prod

FROM node:20-alpine AS builder
WORKDIR /app
RUN corepack enable pnpm

COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

RUN pnpm install --frozen-lockfile --offline
RUN pnpm run build --filter=api

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
EXPOSE 3001

RUN corepack enable pnpm

COPY --from=builder /app/apps/api/dist ./apps/api/dist
COPY --from=builder /app/apps/api/package.json ./apps/api/package.json
COPY --from=builder /app/apps/api/prisma ./apps/api/prisma
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

WORKDIR /app/apps/api

CMD ["pnpm", "start"]
